// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewUsuarioSistema struct {
	Nombre          string  `json:"nombre"`
	ApellidoPaterno *string `json:"apellido_paterno"`
	ApellidoMaterno *string `json:"apellido_materno"`
	Correo          string  `json:"correo"`
	Telefono        string  `json:"telefono"`
	Password        string  `json:"password"`
}

type Paginacion struct {
	Pagina int `json:"pagina"`
	Limite int `json:"limite"`
}

type Persona struct {
	ID              string  `json:"id"`
	Nombre          string  `json:"nombre"`
	ApellidoPaterno *string `json:"apellido_paterno"`
	ApellidoMaterno *string `json:"apellido_materno"`
	Correo          string  `json:"correo"`
	Telefono        string  `json:"telefono"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
